apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opamp

resources:
  - postgres.yaml
  - control-plane.yaml

images:
  - name: ghcr.io/feriva22/opamp-centralized
    newName: ghcr.io/feriva22/opamp-centralized
    newTag: latest
